language: node_js
node_js:
  - "stable"
install:
  - npm install -g firebase-tools
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master